server:
  port: 8000
spring:
  application:
    name: Api-Service
  data:
    mongodb:
      uri: mongodb+srv://sai:sai@pinninti-sai-sukumar.lvnkc.mongodb.net/User?retryWrites=true&w=majority

zuul:
  routes:
    Api-Service:
       url : http://localhost:9000/
    FarmerService:
      url : http://localhost:8082/

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

