zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    FarmerService:
      path: /farmer/**
      serviceId: FarmerService
    SecurityService:
      path: /sec/**
      serviceId: SecurityService

server:
  port: 9000

spring:
  application:
    name: Api-Service
  data:
    mongodb:
      uri: mongodb+srv://sai:sai@pinninti-sai-sukumar.lvnkc.mongodb.net/User?retryWrites=true&w=majority
