zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    FarmerService:
      path: /farmer/**
      serviceId: FarmerService
    SecurityService:
      path: /sec/**
      serviceId: SecurityService

server:
  port: 8079

spring:
  application:
    name: Api-Service
