server:
  port: 9000
spring:
  application:
    name: SecurityService
  data:
    mongodb:
      uri: mongodb+srv://sai:sai@pinninti-sai-sukumar.lvnkc.mongodb.net/User?retryWrites=true&w=majority

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
