server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb+srv://sai:sai@pinninti-sai-sukumar.lvnkc.mongodb.net/Farmer?retryWrites=true&w=majority
  application:
    name: FarmerService

  mvc:
    pathmatch:
      matching-strategy:
        ant-path-matcher